### ISSUE TITLE
Integrate with hass-miner?

### ISSUE THREAD

**Issue by wilfredallyn** [wilfredallyn/pyasic_tools#5]
[hass miner](https://github.com/Schnitzel/hass-miner/) is a way to manage miner through [home assistant](https://www.home-assistant.io/). figure out if possible for hass-miner to leverage visualizations from pyasic_tools without duplicating effort

**Comment by b-rowan** [comment]
Home assistant actually provides visualizations directly in the UI, they store a database with a bunch of historical data, so I'm not sure this is needed.

**Comment by b-rowan** [comment]
EG - https://www.home-assistant.io/dashboards/statistics-graph/
